markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: i4TV
host: www.i4tv.org
desc: 利用互联网看电视，利用电视访问互联网。

custom:
    category:
        home: 首页
        products: 产品
    categories:
      - name:  home
        title: 首页

      - name:  products
        title: 产品

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 张平
        email: dqzhangp@163.com
        disqus: 一直写代码                          # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: i4tv                                # GitHub账号
        gravatar: c80b5905637822ee2089224e5d2d3d88  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
